### PR TITLE
Actually, fixed grammar if you don't mind.

### PR DESCRIPTION
**Pull request by Youngestdev**
:wink:

### CODE REVIEW

**Comment by ooade** [comment]
Bleeding edge technologies are somehow in a way new technologies so I don't think it's wrong :sweat_smile:  or do you have other reasons?

**Comment by Youngestdev** [comment]
They are actually two different things, lol. When you say `these`, they weren't listed. and yep. **It's wrong, lol**

**Comment by Youngestdev** [comment]
But again, it looks correct. Lol. Since we're not here to sell English, I'll just close it lol. Pardon my poke nosing.

**Comment by ooade** [comment]
We're all learning. I didn't study English in school :sweat_smile:

**Comment by Youngestdev** [comment]
lol. I didn't study English also. Lol

**Pull request closed without merging**
